import { useState, useEffect, useRef } from "react";
import type { ChangeEvent } from "react";

import {
  collection,
  doc,
  setDoc,
  updateDoc,
  onSnapshot,
  query,
  orderBy,
} from "firebase/firestore";

import type { exerciseObject, setObject } from "../interfaces.ts";

import { db } from "../firebase-config.ts";

import Exercise from "../components/Exercise.tsx";
import SetAdder from "../components/SetAdder.tsx";

function Exercises() {
  const exercisesTotalRef = useRef(0);

  const scroller = useRef(null);

  const [newExerciseName, setNewExerciseName] = useState("");

  const [exerciseIndex, setExerciseIndex] = useState(-1);

  const [isActiveArray, setIsActiveArray] = useState<Array<boolean>>([]);

  const [exercises, setExercises] = useState<Array<exerciseObject>>([]);

  const handleNewAttempt = (index: number) => {
    const newExercises = [...exercises];

    const lastAttempt =
      newExercises[index].attempts[newExercises[index].attempts.length - 1];

    if (lastAttempt?.length !== 0) {
      newExercises[index].attempts.push([]);

      interface Dictionary {
        [key: string]: unknown;
      }

      const attemptArray: Dictionary[] = [];

      newExercises[index].attempts.forEach((subAttempt) => {
        const myObject: Dictionary = {};

        subAttempt.forEach((value, index) => {
          const indexString = index.toString();
          myObject[indexString] = value;
        });

        attemptArray.push(myObject);
      });

      const newFirestoreDocData = {
        id: newExercises[index].id,
        name: newExercises[index].name,
        attempts: attemptArray,
        order: newExercises[index].order,
      };

      const exerciseRef = doc(db, "exercises", newExercises[index].id);

      updateDoc(exerciseRef, newFirestoreDocData);
    }
  };

  const handleNewExercise = () => {
    const exercisesRef = doc(collection(db, "exercises"));

    const autoGeneratedId = exercisesRef.id;

    const newExercise = {
      id: autoGeneratedId,
      name: newExerciseName,
      attempts: [],
      order: exercisesTotalRef.current,
    };

    setDoc(exercisesRef, newExercise);

    setNewExerciseName("");
  };

  const handleNewSet = (newSet: setObject) => {
    const newExercises = [...exercises];
    newExercises[exerciseIndex].attempts[
      newExercises[exerciseIndex].attempts.length - 1
    ].push(newSet);

    interface Dictionary {
      [key: string]: unknown;
    }

    const attemptArray: Dictionary[] = [];

    newExercises[exerciseIndex].attempts.forEach((subAttempt) => {
      const myObject: Dictionary = {};

      subAttempt.forEach((value, index) => {
        const indexString = index.toString();
        myObject[indexString] = value;
      });

      attemptArray.push(myObject);
    });

    const newFirestoreDocData = {
      id: newExercises[exerciseIndex].id,
      name: newExercises[exerciseIndex].name,
      attempts: attemptArray,
    };

    const exerciseRef = doc(db, "exercises", newExercises[exerciseIndex].id);

    updateDoc(exerciseRef, newFirestoreDocData);

    // setNotes("");

    updateScroller();
  };

  const updateScroller = () => {
    setTimeout(() => {
      const thisScroller = scroller.current;
      if (thisScroller) {
        (thisScroller as HTMLElement).scrollTop = (
          thisScroller as HTMLElement
        ).scrollHeight;
      }
    });
  };

  useEffect(() => {
    const tempIsActiveArray = new Array(exercisesTotalRef.current).fill(false);
    tempIsActiveArray[exerciseIndex] = true;
    setIsActiveArray(tempIsActiveArray);
    updateScroller();
    // This is when I should set the input values of the Adder to the last values in the set
  }, [exerciseIndex]);

  useEffect(() => {
    const q = query(collection(db, "exercises"), orderBy("order", "asc"));

    const unsubscribe = onSnapshot(q, (querySnapshot) => {
      const dataFromFirestore: exerciseObject[] = [];

      querySnapshot.forEach((doc) => {
        const thisExerciseAttempts: Array<Array<setObject>> = [];

        const thisExercise = doc.data();

        thisExercise.attempts.forEach(
          (subAttempt: { [s: string]: unknown } | ArrayLike<unknown>) => {
            const valuesArray = Object.values(subAttempt) as setObject[];
            thisExerciseAttempts.push(valuesArray);
          },
        );

        const rowFromFirestore: exerciseObject = {
          id: thisExercise.id,
          name: thisExercise.name,
          attempts: thisExerciseAttempts,
          order: thisExercise.order,
        };

        dataFromFirestore.push(rowFromFirestore);
      });

      setExercises(dataFromFirestore);

      if (dataFromFirestore.length - exercisesTotalRef.current === 1) {
        setExerciseIndex(exercisesTotalRef.current);
      }
      exercisesTotalRef.current = dataFromFirestore.length;
    });

    return () => unsubscribe();
  }, []);

  const handleChange = (
    event: ChangeEvent<HTMLInputElement> | ChangeEvent<HTMLTextAreaElement>,
  ) => {
    const theInput = event.target as HTMLInputElement;
    // const newValue = parseInt(theInput.value, 10);

    switch (theInput.id) {
      // case "reps":
      //   setReps(newValue);
      //   break;
      // case "weight":
      //   setWeight(newValue);
      //   break;
      // case "notes":
      //   setNotes(theInput.value);
      //   break;
      case "name":
        setNewExerciseName(theInput.value);
        break;
    }
  };

  // const trySetReps = (newValue: number) => {
  //   if (newValue >= 0 && newValue <= 99) {
  //     setReps(newValue);
  //   }
  // };

  // const trySetWeight = (newValue: number) => {
  //   if (newValue >= 0 && newValue <= 300) {
  //     setWeight(newValue);
  //   }
  // };

  return (
    <div className="flex h-full flex-col">
      <div className="flex bg-gray-500 p-4 shadow-md">
        <input
          id="name"
          type="text"
          className="text-md mr-4 ml-auto h-8 w-full rounded-md border-1 border-dotted bg-gray-100 p-3 text-left font-bold tabular-nums"
          onChange={handleChange}
          value={newExerciseName}
        />
        <button
          className="block h-8 rounded-md border-1 px-3 text-white"
          onClick={handleNewExercise}
        >
          Add&nbsp;Exercise
        </button>
      </div>
      <div className="mb-4 border-b-2 border-gray-300 bg-gray-500 p-4">
        {exercises.map((item, index) => (
          <button
            key={index}
            className={`mr-2 rounded-md border-1 border-white px-3 py-1 text-lg text-white ${index === exerciseIndex && "bg-black"}`}
            onClick={() => {
              setExerciseIndex(index);
            }}
          >
            {item.name}
          </button>
        ))}
      </div>
      <div
        ref={scroller}
        className="[&>*]:last]:animate-pulse max-h-full flex-1 overflow-y-auto"
      >
        {exercises.map((item, index) => (
          <Exercise
            data={item}
            key={index}
            isActive={isActiveArray[index]}
            newAttempt={() => {
              handleNewAttempt(index);
            }}
          />
        ))}
      </div>
      <SetAdder handleNewSet={handleNewSet} />
    </div>
  );
}

export default Exercises;
