import { useState, useEffect, useRef } from "react";
import type { ChangeEvent } from "react";
import type { exerciseObject, setObject } from "../interfaces.ts";

import {
  collection,
  doc,
  setDoc,
  updateDoc,
  onSnapshot,
  query,
  orderBy,
} from "firebase/firestore";

import { db } from "../firebase-config.ts";

import Exercise from "../components/Exercise.tsx";

function Exercises() {
  const exerciseTotalRef = useRef(0); // do i need this or can I read this quickly from something?

  const scroller = useRef(null);

  const [newExerciseName, setNewExerciseName] = useState("");

  const [exerciseIndex, setExerciseIndex] = useState(0);

  const [isActiveArray, setIsActiveArray] = useState<Array<boolean>>([]);

  const [exercises, setExercises] = useState<Array<exerciseObject>>([]);

  const [reps, setReps] = useState(3);
  const [weight, setWeight] = useState(50);
  const [notes, setNotes] = useState("");

  const handleNewAttempt = (index: number) => {
    const newExercises = [...exercises];

    const lastAttempt =
      newExercises[index].attempts[newExercises[index].attempts.length - 1];

    if (lastAttempt?.length !== 0) {
      newExercises[index].attempts.push([]);

      interface Dictionary {
        [key: string]: unknown;
      }

      const attemptArray: Dictionary[] = [];

      newExercises[index].attempts.forEach((subAttempt) => {
        const myObject: Dictionary = {};

        subAttempt.forEach((value, index) => {
          const indexString = index.toString();
          myObject[indexString] = value;
        });

        attemptArray.push(myObject);
      });

      const newFirestoreDocData = {
        id: newExercises[index].id,
        name: newExercises[index].name,
        attempts: attemptArray,
        order: newExercises[index].order,
      };

      const exerciseRef = doc(db, "exercises", newExercises[index].id);

      updateDoc(exerciseRef, newFirestoreDocData);
    }
  };

  const handleNewExercise = () => {
    const exercisesRef = doc(collection(db, "exercises"));

    const autoGeneratedId = exercisesRef.id;

    const newExercise = {
      id: autoGeneratedId,
      name: newExerciseName,
      attempts: [],
      order: exerciseTotalRef.current,
    };

    setDoc(exercisesRef, newExercise);

    setNewExerciseName("");
  };

  const handleNewSet = (index: number, newSet: setObject) => {
    const newExercises = [...exercises];
    newExercises[index].attempts[newExercises[index].attempts.length - 1].push(
      newSet,
    );

    interface Dictionary {
      [key: string]: unknown;
    }

    const attemptArray: Dictionary[] = [];

    newExercises[index].attempts.forEach((subAttempt) => {
      const myObject: Dictionary = {};

      subAttempt.forEach((value, index) => {
        const indexString = index.toString();
        myObject[indexString] = value;
      });

      attemptArray.push(myObject);
    });

    const newFirestoreDocData = {
      id: newExercises[index].id,
      name: newExercises[index].name,
      attempts: attemptArray,
    };

    const exerciseRef = doc(db, "exercises", newExercises[index].id);

    updateDoc(exerciseRef, newFirestoreDocData);

    setNotes("");

    updateScroller();
  };

  const updateScroller = () => {
    setTimeout(() => {
      const thisScroller = scroller.current;
      if (thisScroller) {
        (thisScroller as HTMLElement).scrollTop = (
          thisScroller as HTMLElement
        ).scrollHeight;
      }
    });
  };

  useEffect(() => {
    const tempIsActiveArray = [];

    for (let i = 0; i < exerciseTotalRef.current; i++) {
      tempIsActiveArray[i] = false;
      if (exerciseIndex === i) {
        tempIsActiveArray[i] = true;
      }
    }

    setIsActiveArray(tempIsActiveArray);
    updateScroller();
  }, [exerciseIndex]);

  useEffect(() => {
    const q = query(collection(db, "exercises"), orderBy("order", "asc"));

    const unsubscribe = onSnapshot(q, (querySnapshot) => {
      const dataFromFirestore: exerciseObject[] = [];

      querySnapshot.forEach((doc) => {
        const thisExerciseAttempts: Array<Array<setObject>> = [];

        const thisExercise = doc.data();

        thisExercise.attempts.forEach(
          (subAttempt: { [s: string]: unknown } | ArrayLike<unknown>) => {
            const valuesArray = Object.values(subAttempt) as setObject[];
            thisExerciseAttempts.push(valuesArray);
          },
        );

        const rowFromFirestore: exerciseObject = {
          id: thisExercise.id,
          name: thisExercise.name,
          attempts: thisExerciseAttempts,
          order: thisExercise.order,
        };

        dataFromFirestore.push(rowFromFirestore);
      });

      setExercises(dataFromFirestore);

      if (dataFromFirestore.length - exerciseTotalRef.current === 1) {
        setExerciseIndex(exerciseTotalRef.current);
      }
      exerciseTotalRef.current = dataFromFirestore.length;
    });

    return () => unsubscribe();
  }, []);

  const handleChange = (
    event: ChangeEvent<HTMLInputElement> | ChangeEvent<HTMLTextAreaElement>,
  ) => {
    const theInput = event.target as HTMLInputElement;
    const newValue = parseInt(theInput.value, 10);

    switch (theInput.id) {
      case "reps":
        setReps(newValue);
        break;
      case "weight":
        setWeight(newValue);
        break;
      case "notes":
        setNotes(theInput.value);
        break;
      case "name":
        setNewExerciseName(theInput.value);
        break;
    }
  };

  const trySetReps = (newValue: number) => {
    if (newValue >= 0 && newValue <= 99) {
      setReps(newValue);
    }
  };

  const trySetWeight = (newValue: number) => {
    if (newValue >= 0 && newValue <= 300) {
      setWeight(newValue);
    }
  };

  return (
    <div className="flex h-full flex-col">
      <div className="flex bg-gray-500 p-4 shadow-md">
        <input
          id="name"
          type="text"
          className="text-md mr-4 ml-auto h-8 w-full rounded-md border-1 border-dotted bg-gray-100 p-3 text-left font-bold tabular-nums"
          onChange={handleChange}
          value={newExerciseName}
        />

        <button
          className="block h-8 rounded-md border-1 px-3 text-white"
          onClick={handleNewExercise}
        >
          Add&nbsp;Exercise
        </button>
      </div>

      <div className="mb-4 border-b-2 border-gray-300 bg-gray-500 p-4">
        {exercises.map((item, index) => (
          <button
            key={index}
            className={`mr-2 rounded-md border-1 border-white px-3 py-1 text-lg text-white ${index === exerciseIndex && "bg-black"}`}
            onClick={() => {
              setExerciseIndex(index);
            }}
          >
            {item.name}
          </button>
        ))}
      </div>

      <div
        ref={scroller}
        className="[&>*]:last]:animate-pulse max-h-full flex-1 overflow-y-auto"
      >
        {exercises.map((item, index) => (
          <Exercise
            data={item}
            key={index}
            isActive={isActiveArray[index]}
            newAttempt={() => {
              handleNewAttempt(index);
            }}
          />
        ))}
      </div>
      <div className="mx-auto mt-4 flex w-full flex-col border-t-1 border-white bg-gray-500 py-4">
        <div className="flex justify-center gap-12 pt-3 pb-6">
          <div className="flex h-full">
            <div className="flex-col">
              <div className="mb-6 text-center text-sm font-bold">Reps</div>
              <div className="flex">
                <div className="flex flex-col gap-3">
                  <button
                    className="block h-10 w-10 rounded-sm border border-gray-900 bg-gray-100 text-xl font-bold shadow-md"
                    onClick={() => trySetReps(reps + 1)}
                  >
                    <div className="relative -top-[2px]">+</div>
                  </button>
                  <button
                    className="block h-10 w-10 rounded-sm border border-gray-900 bg-gray-100 text-xl font-bold shadow-md"
                    onClick={() => trySetReps(reps - 1)}
                  >
                    <div className="relative -top-[1px]">–</div>
                  </button>
                </div>
                <input
                  id="reps"
                  type="text"
                  className="mt-4 ml-6 h-10 w-12 rounded-md border-1 border-dotted bg-gray-100 pr-3 text-right text-xl font-bold tabular-nums"
                  value={reps}
                  onChange={handleChange}
                />
              </div>
            </div>
          </div>
          <div className="flex flex-col border-r-1 border-l-1 border-gray-300 px-12 font-bold">
            <div className="mb-6 text-center text-sm">Weight</div>
            <div className="flex">
              <input
                id="weight"
                type="text"
                className="mt-4 mr-6 ml-auto h-10 w-26 rounded-md border-1 border-dotted bg-gray-100 pr-5 text-right text-xl font-bold tabular-nums"
                value={weight + "lbs"}
                onChange={handleChange}
              />
              <div className="flex flex-col gap-3">
                <button
                  className="block h-10 w-10 rounded-sm border-1 border-gray-900 bg-gray-100 text-xl font-bold shadow-md"
                  onClick={() => trySetWeight(weight + 1)}
                >
                  <div className="relative -top-[2px]">+</div>
                </button>
                <button
                  className="block h-10 w-10 rounded-sm border-1 border-gray-900 bg-gray-100 text-xl font-bold shadow-md"
                  onClick={() => trySetWeight(weight - 1)}
                >
                  <div className="relative -top-[1px]">–</div>
                </button>
              </div>
            </div>
          </div>
          <div className="p-4">
            <button
              className={`block h-full w-25 flex-1 shrink-0 rounded-md border-1 border-gray-500 bg-green-600 font-black text-white shadow-md`}
              onClick={() => {
                handleNewSet(exerciseIndex, {
                  reps: reps,
                  weight: weight,
                  notes: notes,
                  date: Date.now(),
                });
              }}
            >
              Add Set
            </button>
          </div>
        </div>
        <div className="flex border-t-1 border-gray-400 px-6 py-4 grayscale-70">
          <div className="flex max-h-max w-full self-center-safe">
            <div className="mt-3 w-12 pr-4 text-sm font-bold">Notes</div>
            <input
              type="text"
              id="notes"
              className="ml-4 h-full w-full rounded-md border-1 border-dotted bg-gray-100 p-3 text-left text-base font-bold tabular-nums"
              value={notes}
              onChange={handleChange}
            />
          </div>
        </div>
      </div>
    </div>
  );
}

export default Exercises;
